/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_telemetryviewer_service_BinaryReader */

#ifndef _Included_com_example_telemetryviewer_service_BinaryReader
#define _Included_com_example_telemetryviewer_service_BinaryReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_telemetryviewer_service_BinaryReader
 * Method:    readData
 * Signature: (Ljava/lang/String;)[Lcom/example/telemetryviewer/models/TelemetryIndex;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_telemetryviewer_service_BinaryReader_readData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_telemetryviewer_service_BinaryReader
 * Method:    getData
 * Signature: (II)Lcom/example/telemetryviewer/models/TelemetryData;
 */
JNIEXPORT jobject JNICALL Java_com_example_telemetryviewer_service_BinaryReader_getData
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
